# Generated by Django 5.0.6 on 2024-06-11 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='APIKey',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(db_index=True, max_length=100)),
                ('secret', models.CharField(db_index=True, max_length=100)),
            ],
            options={
                'db_table': 'apikeys',
            },
        ),
    ]
