# Generated by Django 5.0.6 on 2024-06-11 18:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('l2pay', '0002_apikey_enabled'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='apikey',
            options={'verbose_name': 'APIKeys', 'verbose_name_plural': 'APIKeys'},
        ),
        migrations.AddField(
            model_name='apikey',
            name='user',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='apikeys', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Payments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_created=True, db_index=True)),
                ('created_at', models.DateTimeField(auto_created=True, db_index=True)),
                ('expired_at', models.DateTimeField(db_index=True)),
                ('network', models.CharField(choices=[('Starknet', 'Starknet'), ('zkSync', 'Zksync'), ('XLAYER', 'Xlayer'), ('KakarotZkEVM', 'Kakarot'), ('Blast', 'Blast')], db_index=True, default='Starknet', max_length=20)),
                ('currency', models.CharField(choices=[('USDT', 'Usdt'), ('USDC', 'Usdc'), ('STRK', 'Strk'), ('BTC', 'Btc'), ('ETH', 'Eth')], db_index=True, default='USDC', max_length=10)),
                ('value', models.DecimalField(db_index=True, decimal_places=3, max_digits=12)),
                ('state', models.CharField(choices=[('OPEN', 'Open'), ('PROCESSING', 'Processing'), ('SUCCEED', 'Succeed'), ('FAILED', 'Failed')], db_index=True, default='OPEN', max_length=10)),
                ('external_order_id', models.CharField(db_index=True, max_length=100)),
                ('external_order_title', models.CharField(db_index=True, max_length=100)),
                ('external_order_desc', models.CharField(default='', max_length=100, null=True)),
                ('external_image_url', models.CharField(default='', max_length=200, null=True)),
                ('tx_hash', models.CharField(default='', max_length=200, null=True)),
                ('paid_at', models.DateTimeField(db_index=True, null=True)),
                ('paid_asset', models.CharField(choices=[('USDT', 'Usdt'), ('USDC', 'Usdc'), ('STRK', 'Strk'), ('BTC', 'Btc'), ('ETH', 'Eth')], db_index=True, default='USDC', max_length=10)),
                ('paid_amount', models.DecimalField(decimal_places=10, max_digits=20, null=True)),
                ('paid_usd_rate', models.DecimalField(decimal_places=4, max_digits=10, null=True)),
                ('fee_asset', models.CharField(choices=[('USDT', 'Usdt'), ('USDC', 'Usdc'), ('STRK', 'Strk'), ('BTC', 'Btc'), ('ETH', 'Eth')], db_index=True, default='USDC', max_length=10)),
                ('fee_amount', models.DecimalField(decimal_places=10, max_digits=20, null=True)),
                ('net_asset', models.CharField(choices=[('USDT', 'Usdt'), ('USDC', 'Usdc'), ('STRK', 'Strk'), ('BTC', 'Btc'), ('ETH', 'Eth')], db_index=True, default='USDC', max_length=10)),
                ('net_amount', models.DecimalField(decimal_places=10, max_digits=20, null=True)),
                ('metadata', models.JSONField(db_index=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Payments',
                'verbose_name_plural': 'Payments',
                'db_table': 'payments',
            },
        ),
    ]
