# Generated by Django 5.0.6 on 2024-06-13 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('l2pay', '0005_alter_settings_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payments',
            name='currency',
            field=models.CharField(choices=[('USDT', 'Usdt'), ('USDC', 'Usdc'), ('STRK', 'Strk'), ('BTC', 'Btc'), ('ETH', 'Eth')], db_index=True, default='ETH', max_length=10),
        ),
        migrations.AlterField(
            model_name='payments',
            name='value',
            field=models.DecimalField(db_index=True, decimal_places=8, max_digits=19),
        ),
    ]
