# Generated by Django 5.0.6 on 2024-06-13 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('l2pay', '0006_alter_payments_currency_alter_payments_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payments',
            name='created_at',
            field=models.DateTimeField(auto_created=True, auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='payments',
            name='updated_at',
            field=models.DateTimeField(auto_created=True, auto_now_add=True, db_index=True),
        ),
    ]
