# Generated by Django 5.0.6 on 2024-06-13 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("l2pay", "0008_merchantkey"),
    ]

    operations = [
        migrations.AddField(
            model_name="payments",
            name="pay_wallet",
            field=models.CharField(
                db_index=True, default="null_wallet", max_length=150
            ),
            preserve_default=False,
        ),
    ]
