# Generated by Django 5.0.6 on 2024-06-13 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('l2pay', '0009_payments_pay_wallet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payments',
            name='fee_asset',
            field=models.CharField(choices=[('USDT', 'Usdt'), ('USDC', 'Usdc'), ('STRK', 'Strk'), ('BTC', 'Btc'), ('ETH', 'Eth')], db_index=True, default='ETH', max_length=10),
        ),
        migrations.AlterField(
            model_name='payments',
            name='net_asset',
            field=models.CharField(choices=[('USDT', 'Usdt'), ('USDC', 'Usdc'), ('STRK', 'Strk'), ('BTC', 'Btc'), ('ETH', 'Eth')], db_index=True, default='ETH', max_length=10),
        ),
        migrations.AlterField(
            model_name='payments',
            name='paid_asset',
            field=models.CharField(choices=[('USDT', 'Usdt'), ('USDC', 'Usdc'), ('STRK', 'Strk'), ('BTC', 'Btc'), ('ETH', 'Eth')], db_index=True, default='ETH', max_length=10),
        ),
    ]
