# Generated by Django 5.0.6 on 2024-06-14 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('l2pay', '0011_transfer'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserBalance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_created=True, auto_now_add=True, db_index=True)),
                ('network', models.CharField(choices=[('Starknet', 'Starknet'), ('zkSync', 'Zksync'), ('XLAYER', 'Xlayer'), ('KakarotZkEVM', 'Kakarot'), ('Blast', 'Blast')], db_index=True, default='Starknet', max_length=20)),
                ('currency', models.CharField(choices=[('USDT', 'Usdt'), ('USDC', 'Usdc'), ('STRK', 'Strk'), ('BTC', 'Btc'), ('ETH', 'Eth')], db_index=True, default='ETH', max_length=10)),
                ('value', models.DecimalField(db_index=True, decimal_places=8, default=0, max_digits=19)),
            ],
        ),
        migrations.AlterField(
            model_name='payments',
            name='state',
            field=models.CharField(choices=[('OPEN', 'Open'), ('PROCESSING', 'Processing'), ('SUCCEED', 'Succeed'), ('EXPIRED', 'Expired')], db_index=True, default='OPEN', max_length=10),
        ),
    ]
