# Generated by Django 5.0.6 on 2024-06-14 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('l2pay', '0013_userbalance_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='settings',
            name='updated_at',
            field=models.DateTimeField(auto_created=True, auto_now_add=True),
        ),
    ]
